# -*- mode: ruby -*-

$script = <<-SCRIPT
echo Starting provisioning...

echo Installing Mate Desktop
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y ubuntu-mate-desktop^

echo Getting rid of libre office
apt-get remove -y --purge libreoffice* evolution* rhythmbox* celluloid* cheese*
apt-get clean
apt-get autoremove

locale-gen zh_CN
locale-gen zh_CN.UTF-8
update-locale LANG=zh_CN.UTF-8
update-locale LANGUAGE=zh_CN.UTF-8

localectl set-x11-keymap us

echo Finished provisioning...
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.1.12"

  # see https://subscription.packtpub.com/book/virtualization-&-cloud/9781786464910/1/ch01lvl1sec12/enabling-virtualbox-guest-additions-in-vagrant
  # vagrant vbguest --do install
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  
  config.vm.synced_folder "shared_data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.memory = "4096"
     vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
  end

  config.vm.provision "shell", inline: $script

end
